"""Add assignment distribution tables and relationship

Revision ID: 16b80164c38d
Revises: 
Create Date: 2025-04-16 12:49:43.939138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b80164c38d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assign_to_all_students', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_distributions_assessment_id'), 'assignment_distributions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assignment_distributions_assigned_at'), 'assignment_distributions', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_assignment_distributions_assigned_by_user_id'), 'assignment_distributions', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_assignment_distributions_id'), 'assignment_distributions', ['id'], unique=False)
    op.create_index(op.f('ix_assignment_distributions_section_id'), 'assignment_distributions', ['section_id'], unique=False)
    op.create_table('assignment_distribution_students',
    sa.Column('assignment_distribution_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_distribution_id'], ['assignment_distributions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_distribution_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_distribution_students')
    op.drop_index(op.f('ix_assignment_distributions_section_id'), table_name='assignment_distributions')
    op.drop_index(op.f('ix_assignment_distributions_id'), table_name='assignment_distributions')
    op.drop_index(op.f('ix_assignment_distributions_assigned_by_user_id'), table_name='assignment_distributions')
    op.drop_index(op.f('ix_assignment_distributions_assigned_at'), table_name='assignment_distributions')
    op.drop_index(op.f('ix_assignment_distributions_assessment_id'), table_name='assignment_distributions')
    op.drop_table('assignment_distributions')
    # ### end Alembic commands ###
