"""add_completed_fields_to_homeworks

Revision ID: 3173921e7b44
Revises: a5972708f990
Create Date: 2025-06-25 15:29:55.166681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '3173921e7b44'
down_revision: Union[str, Sequence[str], None] = 'a5972708f990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('completed', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('homeworks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'completed_at')
    op.drop_column('homeworks', 'completed')
    # ### end Alembic commands ###