"""remove term id from lesson

Revision ID: a5972708f990
Revises: 1e0cc7606a13
Create Date: 2025-06-24 11:43:34.584370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5972708f990'
down_revision: Union[str, Sequence[str], None] = '1e0cc7606a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lessons_ibfk_2'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'term_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('term_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('lessons_ibfk_2'), 'lessons', 'terms', ['term_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
